"""Create stage 2 market foundations.

Revision ID: 20260715_0007
Revises: 20260715_0006
Create Date: 2026-07-15 08:07:23.831873
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "20260715_0007"
down_revision: str | None = "20260715_0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

IMMUTABLE_TABLES = (
    "provider_config_version",
    "provider_capability_setting",
    "provider_circuit_history",
    "provider_mutation_request",
    "security_master_version",
    "security_revision",
    "security_universe_snapshot",
    "security_universe_snapshot_item",
    "trading_calendar_version",
    "trading_calendar_day",
    "trading_session",
)


def _seed_provider_config() -> None:
    op.execute(
        sa.text(
            """
            INSERT INTO provider_config_version
                (id, version, provider_code, reason)
            VALUES
                ('10000000-0000-0000-0000-000000000001', 1, 'eastmoney',
                 'initial supported configuration'),
                ('10000000-0000-0000-0000-000000000002', 1, 'sina',
                 'initial supported configuration')
            """
        )
    )
    rows = (
        (
            "20000000-0000-0000-0000-000000000001",
            "eastmoney",
            "SECURITY_MASTER",
            0,
            False,
        ),
        (
            "20000000-0000-0000-0000-000000000002",
            "eastmoney",
            "REALTIME_QUOTE_BATCH",
            0,
            True,
        ),
        (
            "20000000-0000-0000-0000-000000000003",
            "eastmoney",
            "DAILY_BAR_UNADJUSTED",
            0,
            False,
        ),
        (
            "20000000-0000-0000-0000-000000000004",
            "eastmoney",
            "HISTORICAL_DAILY_UNADJUSTED",
            0,
            False,
        ),
        (
            "20000000-0000-0000-0000-000000000005",
            "eastmoney",
            "HISTORICAL_DAILY_QFQ",
            0,
            False,
        ),
        (
            "20000000-0000-0000-0000-000000000006",
            "sina",
            "REALTIME_QUOTE_BATCH",
            1,
            False,
        ),
    )
    table = sa.table(
        "provider_capability_setting",
        sa.column("id", sa.UUID()),
        sa.column("config_version", sa.Integer()),
        sa.column("provider_code", sa.String()),
        sa.column("capability", sa.String()),
        sa.column("enabled", sa.Boolean()),
        sa.column("priority", sa.Integer()),
        sa.column("concurrency", sa.Integer()),
        sa.column("rate_per_second", sa.Float()),
        sa.column("timeout_seconds", sa.Float()),
        sa.column("auto_switch", sa.Boolean()),
    )
    op.bulk_insert(
        table,
        [
            {
                "id": row_id,
                "config_version": 1,
                "provider_code": provider,
                "capability": capability,
                "enabled": True,
                "priority": priority,
                "concurrency": 2,
                "rate_per_second": 2.0,
                "timeout_seconds": 5.0,
                "auto_switch": auto_switch,
            }
            for row_id, provider, capability, priority, auto_switch in rows
        ],
    )


def _protect_immutable_facts() -> None:
    op.execute(
        """
        CREATE FUNCTION reject_stage2_fact_mutation()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'stage 2 historical facts are append-only';
        END;
        $$ LANGUAGE plpgsql
        """
    )
    for table_name in IMMUTABLE_TABLES:
        op.execute(
            f"CREATE TRIGGER {table_name}_append_only "
            f"BEFORE UPDATE OR DELETE ON {table_name} "
            "FOR EACH ROW EXECUTE FUNCTION reject_stage2_fact_mutation()"
        )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_capability_setting",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("config_version", sa.Integer(), nullable=False),
        sa.Column("provider_code", sa.String(length=32), nullable=False),
        sa.Column("capability", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("concurrency", sa.Integer(), nullable=False),
        sa.Column("rate_per_second", sa.Float(), nullable=False),
        sa.Column("timeout_seconds", sa.Float(), nullable=False),
        sa.Column("auto_switch", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "concurrency BETWEEN 1 AND 32",
            name=op.f("ck_provider_capability_setting_concurrency_range"),
        ),
        sa.CheckConstraint(
            "priority >= 0",
            name=op.f("ck_provider_capability_setting_priority_nonnegative"),
        ),
        sa.CheckConstraint(
            "rate_per_second > 0",
            name=op.f("ck_provider_capability_setting_rate_positive"),
        ),
        sa.CheckConstraint(
            "timeout_seconds > 0",
            name=op.f("ck_provider_capability_setting_timeout_positive"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_capability_setting")),
        sa.UniqueConstraint(
            "config_version",
            "provider_code",
            "capability",
            name=op.f("uq_provider_capability_setting_config_version"),
        ),
    )
    op.create_table(
        "provider_circuit_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_code", sa.String(length=32), nullable=False),
        sa.Column("capability", sa.String(length=64), nullable=False),
        sa.Column("from_state", sa.String(length=32), nullable=False),
        sa.Column("to_state", sa.String(length=32), nullable=False),
        sa.Column("reason_code", sa.String(length=100), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_circuit_history")),
    )
    op.create_table(
        "provider_circuit_state",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_code", sa.String(length=32), nullable=False),
        sa.Column("capability", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("cooldown_index", sa.Integer(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "consecutive_failures >= 0",
            name=op.f("ck_provider_circuit_state_failures_nonnegative"),
        ),
        sa.CheckConstraint(
            "cooldown_index BETWEEN 0 AND 2",
            name=op.f("ck_provider_circuit_state_cooldown_index_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_circuit_state")),
        sa.UniqueConstraint(
            "provider_code",
            "capability",
            name=op.f("uq_provider_circuit_state_provider_code"),
        ),
    )
    op.create_table(
        "provider_config_version",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("provider_code", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_config_version")),
        sa.UniqueConstraint(
            "provider_code",
            "version",
            name=op.f("uq_provider_config_version_provider_code"),
        ),
    )
    op.create_table(
        "provider_failure_sample",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_code", sa.String(length=32), nullable=False),
        sa.Column("capability", sa.String(length=64), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=False),
        sa.Column("sample", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_failure_sample")),
    )
    op.create_table(
        "provider_health_state",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_code", sa.String(length=32), nullable=False),
        sa.Column("capability", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_health_state")),
        sa.UniqueConstraint(
            "provider_code",
            "capability",
            name=op.f("uq_provider_health_state_provider_code"),
        ),
    )
    op.create_table(
        "provider_mutation_request",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("request_digest", sa.String(length=64), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("object_id", sa.String(length=128), nullable=False),
        sa.Column(
            "response_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("actor_user_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("trusted_ip", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_mutation_request")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("uq_provider_mutation_request_idempotency_key")
        ),
    )
    op.create_table(
        "security",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("exchange_code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("market", sa.String(length=8), nullable=False),
        sa.Column("security_type", sa.String(length=32), nullable=False),
        sa.Column("listed_on", sa.Date(), nullable=True),
        sa.Column("delisted_on", sa.Date(), nullable=True),
        sa.Column("listing_status", sa.String(length=32), nullable=False),
        sa.Column(
            "is_st", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "is_suspended",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "provider_codes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("master_version", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_version", sa.String(length=160), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "listing_status IN ('LISTED','SUSPENDED','DELISTED','DATA_MISSING')",
            name=op.f("ck_security_listing_status_valid"),
        ),
        sa.CheckConstraint(
            "market IN ('SH','SZ','BJ','HK','US')",
            name=op.f("ck_security_market_valid"),
        ),
        sa.CheckConstraint(
            "security_type IN ('A_SHARE','ETF','CONVERTIBLE_BOND','B_SHARE',"
            "'FUND','INDEX','HK_STOCK','US_STOCK')",
            name=op.f("ck_security_security_type_valid"),
        ),
        sa.CheckConstraint(
            "master_version > 0", name=op.f("ck_security_master_version_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security")),
        sa.UniqueConstraint("symbol", name=op.f("uq_security_symbol")),
    )
    op.create_index(
        "ix_security_name_symbol", "security", ["name", "symbol"], unique=False
    )
    op.create_table(
        "security_master_version",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_version", sa.String(length=160), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("master_version", sa.Integer(), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column(
            "result_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "item_count > 0",
            name=op.f("ck_security_master_version_item_count_positive"),
        ),
        sa.CheckConstraint(
            "master_version > 0",
            name=op.f("ck_security_master_version_master_version_positive"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_master_version")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("uq_security_master_version_idempotency_key")
        ),
        sa.UniqueConstraint(
            "master_version", name=op.f("uq_security_master_version_master_version")
        ),
        sa.UniqueConstraint(
            "source", "source_version", name=op.f("uq_security_master_version_source")
        ),
    )
    op.create_table(
        "security_universe_snapshot",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("master_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "item_count >= 0",
            name=op.f("ck_security_universe_snapshot_item_count_nonnegative"),
        ),
        sa.CheckConstraint(
            "master_version >= 0",
            name=op.f("ck_security_universe_snapshot_master_version_nonnegative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_universe_snapshot")),
    )
    op.create_table(
        "trading_calendar_version",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("market", sa.String(length=16), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_version", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("based_on_version_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "version_number > 0",
            name=op.f("ck_trading_calendar_version_version_number_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["based_on_version_id"],
            ["trading_calendar_version.id"],
            name=op.f(
                "fk_trading_calendar_version_based_on_version_id_trading_calendar_version"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trading_calendar_version")),
        sa.UniqueConstraint(
            "market", "idempotency_key", name="uq_calendar_idempotency_key"
        ),
        sa.UniqueConstraint(
            "market",
            "source",
            "source_version",
            name="uq_calendar_source_version",
        ),
        sa.UniqueConstraint(
            "market", "version_number", name="uq_calendar_version_number"
        ),
    )
    op.create_index(
        "ix_trading_calendar_version_market_created",
        "trading_calendar_version",
        ["market", "created_at"],
        unique=False,
    )
    op.create_table(
        "security_revision",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("security_id", sa.UUID(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("master_version", sa.Integer(), nullable=False),
        sa.Column(
            "changed_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "before_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "after_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "master_version > 0",
            name=op.f("ck_security_revision_master_version_positive"),
        ),
        sa.CheckConstraint(
            "revision_no > 0", name=op.f("ck_security_revision_revision_no_positive")
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
            name=op.f("fk_security_revision_security_id_security"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_revision")),
        sa.UniqueConstraint(
            "security_id", "revision_no", name=op.f("uq_security_revision_security_id")
        ),
    )
    op.create_index(
        "ix_security_revision_master_version",
        "security_revision",
        ["master_version"],
        unique=False,
    )
    op.create_table(
        "security_universe_snapshot_item",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("market", sa.String(length=8), nullable=False),
        sa.Column("security_type", sa.String(length=32), nullable=False),
        sa.Column("listing_status", sa.String(length=32), nullable=False),
        sa.Column("is_st", sa.Boolean(), nullable=False),
        sa.Column("is_suspended", sa.Boolean(), nullable=False),
        sa.Column("master_version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "master_version > 0",
            name=op.f("ck_security_universe_snapshot_item_master_version_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["security_universe_snapshot.id"],
            name=op.f(
                "fk_security_universe_snapshot_item_snapshot_id_security_universe_snapshot"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_universe_snapshot_item")),
        sa.UniqueConstraint(
            "snapshot_id",
            "symbol",
            name=op.f("uq_security_universe_snapshot_item_snapshot_id"),
        ),
    )
    op.create_index(
        "ix_security_universe_item_symbol",
        "security_universe_snapshot_item",
        ["symbol"],
        unique=False,
    )
    op.create_table(
        "trading_calendar_current",
        sa.Column("market", sa.String(length=16), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("pointer_version", sa.Integer(), nullable=False),
        sa.Column(
            "switched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "pointer_version > 0",
            name=op.f("ck_trading_calendar_current_pointer_version_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["trading_calendar_version.id"],
            name=op.f(
                "fk_trading_calendar_current_version_id_trading_calendar_version"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("market", name=op.f("pk_trading_calendar_current")),
    )
    op.create_table(
        "trading_calendar_day",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("is_trading_day", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("override_reason", sa.String(length=500), nullable=True),
        sa.CheckConstraint(
            "status IN ('CONFIRMED','PROVISIONAL','OVERRIDDEN','MISSING')",
            name=op.f("ck_trading_calendar_day_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["trading_calendar_version.id"],
            name=op.f("fk_trading_calendar_day_version_id_trading_calendar_version"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trading_calendar_day")),
        sa.UniqueConstraint(
            "version_id", "trade_date", name=op.f("uq_trading_calendar_day_version_id")
        ),
    )
    op.create_index(
        "ix_trading_calendar_day_date",
        "trading_calendar_day",
        ["trade_date", "version_id"],
        unique=False,
    )
    op.create_table(
        "trading_session",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("calendar_day_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.Time(), nullable=False),
        sa.Column("ends_at", sa.Time(), nullable=False),
        sa.CheckConstraint(
            "sequence > 0", name=op.f("ck_trading_session_sequence_positive")
        ),
        sa.CheckConstraint(
            "starts_at < ends_at", name=op.f("ck_trading_session_time_order_valid")
        ),
        sa.ForeignKeyConstraint(
            ["calendar_day_id"],
            ["trading_calendar_day.id"],
            name=op.f("fk_trading_session_calendar_day_id_trading_calendar_day"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trading_session")),
        sa.UniqueConstraint(
            "calendar_day_id",
            "sequence",
            name="uq_trading_session_sequence",
        ),
        sa.UniqueConstraint(
            "calendar_day_id",
            "starts_at",
            "ends_at",
            name="uq_trading_session_time_range",
        ),
    )
    _seed_provider_config()
    _protect_immutable_facts()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in reversed(IMMUTABLE_TABLES):
        op.execute(f"DROP TRIGGER IF EXISTS {table_name}_append_only ON {table_name}")
    op.execute("DROP FUNCTION IF EXISTS reject_stage2_fact_mutation()")
    op.drop_table("trading_session")
    op.drop_index("ix_trading_calendar_day_date", table_name="trading_calendar_day")
    op.drop_table("trading_calendar_day")
    op.drop_table("trading_calendar_current")
    op.drop_index(
        "ix_security_universe_item_symbol", table_name="security_universe_snapshot_item"
    )
    op.drop_table("security_universe_snapshot_item")
    op.drop_index("ix_security_revision_master_version", table_name="security_revision")
    op.drop_table("security_revision")
    op.drop_index(
        "ix_trading_calendar_version_market_created",
        table_name="trading_calendar_version",
    )
    op.drop_table("trading_calendar_version")
    op.drop_table("security_universe_snapshot")
    op.drop_table("security_master_version")
    op.drop_index("ix_security_name_symbol", table_name="security")
    op.drop_table("security")
    op.drop_table("provider_mutation_request")
    op.drop_table("provider_health_state")
    op.drop_table("provider_failure_sample")
    op.drop_table("provider_config_version")
    op.drop_table("provider_circuit_state")
    op.drop_table("provider_circuit_history")
    op.drop_table("provider_capability_setting")
    # ### end Alembic commands ###
